spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE